ERROR: file magic.py: line 377: sram	LVS mismatch (results in /tmp/openram_bugra_14_temp/sram.lvs.report)

